services:
  raw_data_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8001}:${PORT:-8001}"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8001}
    volumes:
      - ${HOST_IFCB_RAW_DATA_DIR}:/data/raw:ro
