[project]
name = "raw-data-service"
version = "0.1.0"
description = "Serves raw IFCB data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amplify-stateless @ git+https://github.com/WHOIGit/amplify-stateless-microservice.git@v1.3.1",
    "aiofiles",
    "pillow",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages =["raw_service"]

[tool.hatch.metadata]
allow-direct-references = true
